resources:
- repo: self

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'chgeuer-dockerhub'
    action: 'Push an image'
    qualifyImageName: false
    includeLatestTag: true
